<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.*" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.*" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.*" />
    <PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EfToDapper.Core\EfToDapper.Core.csproj" />
    <ProjectReference Include="..\EfToDapper.Data\EfToDapper.Data.csproj" />
  </ItemGroup>
</Project>
